version: '3.3'
services:
  jenkins:
    build: 
      context: .
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    image: jenkins:showroom
    ports:
      - '8080:8080'
      - '8081:8081'
      - '443:8443'
      - '50000:50000'
    volumes:
      - ./data/:/var/jenkins_home/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m