version: '3.3'
services:
  jenkins:
    build: 
      context: .
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    image: jenkins:showroom
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - ./data/:/var/jenkins_home/