security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: false
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: 8081