jobs:
    - script: >
        pipelineJob('jenkins-showroom') {
            branchSources {
                git {
                    id = 'configuration-as-code'
                    remote('https://github.com/jeremychauvet/jenkins-pipelines-showroom')
                }
            }
            orphanedItemStrategy {
                discardOldItems {
                    numToKeep(5)
                }
            }
        }